### ISSUE TITLE
Delete chat

### ISSUE THREAD

**Issue by hazadus** [hazadus/node-messenger#11]
## ToDos

- [x] Create `deleteConversation` query on backend
- [x] Create `deleteConversation` query on frontend
- [x] Wire up delete query with menu item
