### ISSUE TITLE
Delete messages

### ISSUE THREAD

**Issue by hazadus** [hazadus/node-messenger#14]
# ToDos

- [x] Context menu for messages
- [x] Call `createUmamiEvent`
- Mutation
    - [x] `deleteMessage` resolver
    - [x] `DeleteMessage` operation on frontend
    - [x] `useMutation` in context menu
- Subscription
   - [x] `messageDeleted` resolver
   - [x] `MessageDeleted` operation on frontend
   - [x] `useSubscription` on frontend
