### ISSUE TITLE
Configure Docker Compose 🐳

### ISSUE THREAD

**Issue by hazadus** [hazadus/node-messenger#3]
## ToDos

- [x] Configure Docker for frontend
- [ ] Configure Docker for backend
- [ ] Create new VDS
- [ ] Configure Google Auth for additional app domain name
- [ ] Deploy!

## References

- https://stackoverflow.com/questions/24537340/docker-adding-a-file-from-a-parent-directory
- https://github.com/vercel/next.js/blob/canary/examples/with-docker/README.md
- https://github.com/vercel/next.js/tree/canary/examples/with-docker-compose
