### ISSUE TITLE
Features Roadmap 💬🛣️

### ISSUE THREAD

**Issue by hazadus** [hazadus/node-messenger#4]
## Features

- UI
    - [x] #6
    - [ ] #7
    - [ ] #18 
    - [x] 🛎️ Sound effects
        - [x] Play only on new messages
        - [x] Sound on / off option in "main" menu ([persistent in Local Storage](https://www.joshwcomeau.com/react/persisting-react-state-in-localstorage/))
    - [x] Sort conversations list by latest message, desc, when new message arrives
- Various
     - [x] Refactor Prisma schema to single shared file
- Chat enhancements
   - [x] #9
   - "Chat owner" actions
      - [x] #11
      - [ ] Chat Info modal
      - [ ] Add / remove users
      - [ ] Set chat title
    - [ ] "Leave chat" option
   - [ ] System messages (user joined, user leave...)
   - [ ] `isTyping` state for `ConversationParticipant`
   - [ ] User Online state
- Messages enhancements
    - [x] #14
    - [x] Copy Text from messages context menu
    - [ ] Reply to messages (`quotedMessage`)
    - [ ] Edit messages
    - [ ] Forward messages
    - [ ] Pin messages
    - [ ] Upload files
- CI/CD
    - [x] Add Sentry
    - [x] Add Umami tracking and events
    - [x] Write `make` backup script
    - [ ] [Add user](https://pythonspeed.com/articles/root-capabilities-docker-security/) in Docker images
    - [x] #3
- [x] Deploy! 🚀

**Comment by hazadus** [comment]
## User Online State implementation ideas

- Redis for storing userId and last active time
- A middleware on the server that updates last active for every route hit if user is signed in
- Redis key expires after 15 minutes

A separate gql subscription that connects to the output of a Cron job that runs every minute on the minute. The job polls all “Active users” from redis and fires off events when something new is added or something is removed.

Ref: https://www.reddit.com/r/graphql/comments/nw9l2n/comment/hk1zr3p/
