### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by hazadus** [hazadus/node-messenger#6]
## ToDos

- Overall
   - [x] Change "brand" color to purple 
- Chat list navbar:
    - [x] "Create chat" button
    - [x] WhatsApp-like dropdown menu (Profile, Sounds on/off, About app, Logout)
    - [x] Profile info modal (open from menu or click on avatar)
    - [x] About app modal
- Chat List
    - [x] Search box below navbar
    - [x] "Filter unread" button
    - [x] Hide user's avatar in list items
- Messages navbar:
    - [x] Dropdown menu (Chat Info, Delete, Leave)
    - [x] Hide user's avatar in navbar
- Messages:
    - [x] "No chat selected" – style and center 
    - [x] Limit max width of the messages area
    - [x] Auto focus message input
