### ISSUE TITLE
Improve UI 2

### ISSUE THREAD

**Issue by hazadus** [hazadus/node-messenger#7]
## ToDos

- Sounds
    - [x] Play sounds only for new messages (not for all conversation updates) 
- Chat List
    - [x] Fix width for mobile screens
    - [x] Fix width for large screens
    - [x] Fix width to avoid horizontal scrollbar
    - [ ] Tooltips for all usernames
    - [ ] Tooltip for full latest message
    - [x] Vertical scrolling
- Chat context menu
    - [ ] Hide items unavailable to user
    - [ ] Add "Chat Info" item 
- "Create New Chat" modal:
    - [ ] Search as user types 
- Messages:
    - [x] Dates in message area (like Telegram web)
    - [ ] Some kind of "no messages yet" banner
    - [ ] Use "optimistic render" for sent messages so user avatars don't flicker
    - [ ] Show avatar and username in last message only
    - [ ] Hide avatar and username if there's only 2 participants in the chat
    - [ ] Markdown in messages
- Optimise for mobile devices
    - [x] Debug scrolling to new messages on iPad
